<?php
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    
    // 1. Capture and sanitize customer metadata
    $client_name = strip_tags(trim($_POST["client_name"]));
    $client_location = strip_tags(trim($_POST["client_location"]));
    $cart_total = strip_tags(trim($_POST["cart_total"]));
    
    // Decode the JSON cart object generated by our JavaScript front-end code
    $cart_json = $_POST["cart_data"];
    $cart_items = json_decode($cart_json, true);

    // 2. Configure Owner Phone Number
    // Use international format without the "+" sign. (e.g., 263771234567 for Zimbabwe)
    $owner_whatsapp_number = "263770000000"; // <-- PUT THE OWNER'S WHATSAPP NUMBER HERE

    // 3. Construct a beautiful, clean structured text layout for WhatsApp readouts
    $message = "*NEW ANKARA WEAR ORDER*\n\n";
    $message .= "*Customer Details:*\n";
    $message .= "• Name: " . $client_name . "\n";
    $message .= "• Location: " . $client_location . "\n\n";
    
    $message .= "*Items Requested:*\n";
    
    foreach ($cart_items as $item) {
        $item_name = $item['name'];
        $item_qty = $item['quantity'];
        $item_price = $item['price'] * $item_qty;
        
        $message .= "• " . $item_name . " (x" . $item_qty . ") - $" . $item_price . "\n";
    }
    
    $message .= "\n *Estimated Total:* $" . $cart_total . "\n\n";
    $message .= "💬 _Hi! I found these designs on your store page. Let's discuss final tailoring sizes and payment details here._";

    // 4. URL encode the string so spaces, returns, and emojis display natively on WhatsApp
    $encoded_message = urlencode($message);

    // 5. Generate deep-link API routing URL
    $whatsapp_url = "https://wa.me/" . $owner_whatsapp_number . "?text=" . $encoded_message;

    // 6. Instantly warp user directly out to chat thread interface
    header("Location: " . $whatsapp_url);
    exit;

} else {
    // Safety guard fallback redirection link routing back home
    header("Location: store.html");
    exit;
}
?>